# -*- coding: utf-8 -*-
"""customObjectDetection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1puAnFM8ONzohcL36fKNIwBTm_EmKmQ4C

blog refered to : https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html

youtube video : https://www.youtube.com/watch?v=XoMiveY_1Z4

Files:  https://drive.google.com/drive/folders/1-0-R2Qh7M5kWCLyrnNIRtMtjHz1u3VDA?usp=sharing
"""

!pip install tensorflow-gpu

import tensorflow as tf
print(tf.__version__)

"""**Cloning TFOD 2.0 Github**"""

!git clone https://github.com/tensorflow/models.git

cd /content/models/research

"""**Installing protobuf**

"""

!protoc object_detection/protos/*.proto --python_out=.

"""** Installing coco API **"""

!git clone https://github.com/cocodataset/cocoapi.git

cd cocoapi/PythonAPI

#for compiling
!make

cp -r pycocotools /content/models/research

"""## **Installing the Object Detection API**"""

pwd

cd /content/models/research

cp object_detection/packages/tf2/setup.py .

!python -m pip install .

"""## Testing Object Detection API installation"""

!python object_detection/builders/model_builder_tf2_test.py

pwd

cd /content/training_demo/pre-trained-models

!wget http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_resnet101_v1_fpn_640x640_coco17_tpu-8.tar.gz

pwd

!tar -xvf ssd_resnet101_v1_fpn_640x640_coco17_tpu-8.tar.gz

pwd

cd /content/training_demo

# Create train data:
!python generate_tfrecord.py -x /content/training_demo/images/train -l /content/training_demo/annotations/label_map.pbtxt -o /content/training_demo/annotations/train.record

# Create test data:
!python generate_tfrecord.py -x /content/training_demo/images/test -l /content/training_demo/annotations/label_map.pbtxt -o /content/training_demo/annotations/test.record

pwd

cd /content/training_demo

ls

!python model_main_tf2.py --model_dir=/content/training_demo/models/my_ssd_resnet101_v1_fpn --pipeline_config_path=/content/training_demo/models/my_ssd_resnet101_v1_fpn/pipeline.config

#!python model_main_tf2.py --model_dir=/content/training_demo/models/my_ssd_resnet101_v1_fpn --pipeline_config_path=/content/training_demo/models/my_ssd_resnet101_v1_fpn/pipeline.config

#use the folders below and add them to colab or mount them into google drive 
#P.S:this will take some time
#https://drive.google.com/drive/folders/1-0-R2Qh7M5kWCLyrnNIRtMtjHz1u3VDA?usp=sharing

#changing directory to pretrained model folder 
#%cd/content/models/research
#%cd /content/drive/MyDrive/Datasets/training_demo/pre-trained-models

#downloading a pre-trained model from tensorflow repo
#!wget http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_resnet101_v1_fpn_640x640_coco17_tpu-8.tar.gz

#extracting the tar file
#!tar-xvf ssd_resnet101_v1_fpn_640x640_coco17_tpu-8.tar.gz

#pwd

#creating Tensorflow Records

#cd /content/drive/MyDrive/Datasets/training_demo

# Create train data:
#!python generate_tfrecord.py -x /content/drive/MyDrive/Datasets/training_demo/images/train -l /content/drive/MyDrive/Datasets/training_demo/annotations/label_map.pbtxt -o /content/drive/MyDrive/Datasets/training_demo/annotations/train.record

# Create test data:
#!python generate_tfrecord.py -x /content/drive/MyDrive/Datasets/training_demo/images/test -l /content/drive/MyDrive/Datasets/training_demo/annotations/label_map.pbtxt -o /content/drive/MyDrive/Datasets/training_demo/annotations/test.record

#pwd

#ls

#!python model_main_tf2.py --model_dir=/content/drive/MyDrive/Datasets/training_demo/models/my_ssd_resnet101_v1_fpn --pipeline_config_path=/content/drive/MyDrive/Datasets/training_demo/models/my_ssd_resnet101_v1_fpn